// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtROWPDh4yObFTrveicx_6dZSrtYJWqMg',
    appId: '1:107236137414:web:7de04c433dc4d07f72bac7',
    messagingSenderId: '107236137414',
    projectId: 'total-ai-a1859',
    authDomain: 'total-ai-a1859.firebaseapp.com',
    storageBucket: 'total-ai-a1859.firebasestorage.app',
    measurementId: 'G-E9MZTZVFNZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAta7u_5WAT7Bn-FCq6Nn8up2S_pHoTrtM',
    appId: '1:107236137414:android:922702e3f0d8975a72bac7',
    messagingSenderId: '107236137414',
    projectId: 'total-ai-a1859',
    storageBucket: 'total-ai-a1859.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv2wqRB0kGJ9ImQuConp0IT_EPHJzzpDE',
    appId: '1:107236137414:ios:a8c3188869161bee72bac7',
    messagingSenderId: '107236137414',
    projectId: 'total-ai-a1859',
    storageBucket: 'total-ai-a1859.firebasestorage.app',
    iosBundleId: 'com.example.totelai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv2wqRB0kGJ9ImQuConp0IT_EPHJzzpDE',
    appId: '1:107236137414:ios:a8c3188869161bee72bac7',
    messagingSenderId: '107236137414',
    projectId: 'total-ai-a1859',
    storageBucket: 'total-ai-a1859.firebasestorage.app',
    iosBundleId: 'com.example.totelai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtROWPDh4yObFTrveicx_6dZSrtYJWqMg',
    appId: '1:107236137414:web:a4da6bc46169137072bac7',
    messagingSenderId: '107236137414',
    projectId: 'total-ai-a1859',
    authDomain: 'total-ai-a1859.firebaseapp.com',
    storageBucket: 'total-ai-a1859.firebasestorage.app',
    measurementId: 'G-C0MPJGTNCE',
  );
}
